modelproject/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='home')
]

modelproject/modelproject/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from home import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='index'),
    path('users/', include('users.urls')),
    path('formpage/',views.form_name_view,name='form_name'),
    path('signup/', include('signup.urls')),
    path('relativeurls/', include('relativeurls.urls')),
    path('tempinheritance/', include('tempinheritance.urls'))
]

modelproject/relativeurls/urls.py
from django.urls import path
from relativeurls import views

# template tagging
app_name = 'relativeurls'

urlpatterns = [
    path('',views.index),
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other')
]

modelproject/signup/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.email,name='signup')
]

modelproject/tempinheritance/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'tempinheritance'

urlpatterns = [
    path('',views.tempinheritanceview,name='basehtml'),
    path('page1/', views.page1,name='page1'),
    path('page2/', views.page2,name='page2'),
    path('basehtml/', views.basehtml, name='basehtml')
]

modelproject/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.users,name='users')
]

modelproject/home/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
    top_name = models.CharField(max_length=264,unique=True)


    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    name = models.CharField(max_length=264,unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage,on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

modelproject/relativeurls/models.py
from django.db import models

# Create your models here.

modelproject/signup/models.py
from django.db import models

# Create your models here.

class Email(models.Model):
    email = models.EmailField(max_length=254,unique=True)
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)

modelproject/tempinheritance/models.py
from django.db import models

# Create your models here.

modelproject/users/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

    def __str__(self):
        return self.last_name

modelproject/home/forms.py
from django import forms
from django.core import validators

def check_for_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError("Name needs to start with z")

class FormName(forms.Form):
    name = forms.CharField(validators=[check_for_z])
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Entery your email again: ')
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False,
                                widget=forms.HiddenInput,
                                validators=[validators.MaxLengthValidator(0)])

    def clean_botcatcher(self):
        botcatcher = self.cleaned_data['botcatcher']
        if len(botcatcher) > 0:
            raise forms.ValidationError("gotcha bot!")
        return botcatcher

# This method cleans the data for entire form 
    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vemail = all_clean_data['verify_email']

        if email != vemail:
            raise forms.ValidationError("incorrect email")

modelproject/signup/forms.py
from django import forms
from django.core import validators
from .models import Email

class SignupForm(forms.Form):
    firstname = forms.CharField()
    lastname = forms.CharField()
    email = forms.EmailField()

class NewUserForm(forms.ModelForm):
    class Meta:
        model = Email
        fields = '__all__'

modelproject/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import forms

# Create your views here.

def home(request):
    return render(request,'home/index.html')
    
def form_name_view(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            print("VALIDATION SUCCESS")
            print("NAME: "+form.cleaned_data['name'])
            print("EMAIL: "+form.cleaned_data['email'])
            print("TEXT: "+form.cleaned_data['text'])


    return render(request,'home/form.html',{'form':form})

modelproject/relativeurls/views.py
from django.shortcuts import render

# Create your views here.

def index(request):

    return render(request,'relativeurls/index.html')

def other(request):

    return render(request,'relativeurls/other.html')

def relative(request):

    return render(request,'relativeurls/relative_url_templates.html')

modelproject/signup/views.py
from django import forms
from django.shortcuts import render
from . import forms
from signup.forms import NewUserForm

# Create your views here.

def signup_form_view(request):

    form = forms.SignupForm()

    return render(request,'signup/form.html',{'form':form})

def index(request):
    return render(request,'signup/index.html')

def email(request):

    form = NewUserForm()

    if request.method == "POST":
        form = NewUserForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

        else:
            print("Error Form Invalid")

    return render(request,'signup/form.html',{'form':form})

modelproject/tempinheritance/views.py
from django.shortcuts import render

# Create your views here.

def tempinheritanceview(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'tempinheritance/index.html',context_dict)

def page1(request):

    return render(request,'tempinheritance/page1.html')

def page2(request):

    return render(request,'tempinheritance/page2.html')

def basehtml(request):

    return render(request,'tempinheritance/basehtml.html')

modelproject/users/views.py
from django.shortcuts import render
from django.http import HttpResponse
from users.models import User

# Create your views here.

def users(request):
    users_list = User.objects.order_by('first_name')
    first_name_dict = {'firstnames':users_list}
    # my_dict = {'insert_me':'i a from the users.views.py'}
    return render(request,'users/index.html',context=first_name_dict)

modelproject/templates/home/form.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <h1>Fill out the form</h1>

        <div class="container">
            <form method="POST">
                {{form.as_p}}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="save">
            </form>
        </div>
        
        <script src="" async defer></script>
    </body>
</html>

modelproject/templates/home/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Homepage</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <div class= "container">
            <div class="jumbotron">
                <h1>Welcome!</h1>
                <h2>Go to users page for users</h2>
                <h2>Go to formpage for forms</h2>
            </div>

        </div>

        
        <script src="" async defer></script>
    </body>
</html>

modelproject/templates/relativeurls/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <h1>welcom to index</h1>
        
        <script src="" async defer></script>
    </body>
</html>

modelproject/templates/relativeurls/other.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>welcome to other</h1>
        
        <script src="" async defer></script>
    </body>
</html>

modelproject/templates/relativeurls/relative_url_templates.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <h1>welcom to relative url tmepaltes</h1>
        <a href="{% url 'relativeurls:other' %}">Other Page</a>
        <a href="{% url 'admin:index' %}">Admin Index Page</a>
        <a href="{% url 'index' %}">Index</a>      
          
        <script src="" async defer></script>
    </body>
</html>

modelproject/templates/signup/form.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>This is the signup page</h1>
        <form method="POST">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" value="submit">
        </form>

        <script src="" async defer></script>
    </body>
</html>

modelproject/templates/signup/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <h1>this is the signup home page</h1>
        
        <script src="" async defer></script>
    </body>
</html>

modelproject/templates/tempinheritance/basehtml.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <nav class = "navbar navbar-default navbar-static-top navbar-dark bg-dark">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'tempinheritance:basehtml' %}">BRAND</a></li>
                    <li><a class="navbar-link" href="{% url 'tempinheritance:page1' %}">Page1</a></li>
                    <li><a class="navbar-link" href="{% url 'tempinheritance:page2' %}">Page2</a></li>
                </ul>
            </div>
        </nav>
        
        <div class="container">

            {% block body_block %}
            <!-- Anything outside of this will be inherited if you extend -->
            {% endblock %}

        </div>

        <script src="" async defer></script>
    </body>
</html>

modelproject/templates/tempinheritance/index.html
<!DOCTYPE html>

{% extends "tempinheritance/basehtml.html" %}
    {% block body_block %}
    <h1> this is the index page of hte template inheritance lecutre <h1>
        <a href="{% url 'tempinheritance:page1' %}">Page 1</a>
        <a href="{% url 'tempinheritance:page2' %}">Page 2</a>
        
            <h1> {{ text|cut:'hello' }} <h1>
            <h1> {{ number|add:"99" }} <h1>

    {% endblock %}

modelproject/templates/tempinheritance/page1.html
<!DOCTYPE html>

{% extends "tempinheritance/basehtml.html" %}
    {% block body_block %}
        <h1> welcom to page 1 <h1>
        <h2> this is an example of template inheritance <h2>
    {% endblock %}

modelproject/templates/tempinheritance/page2.html
<!DOCTYPE html>

{% extends "tempinheritance/basehtml.html" %}
    {% block body_block %}
        <h1> welcom to page 2 <h1>
        <h2> this is an example of template inheritance <h2>
    {% endblock %}

modelproject/templates/users/index.html
<!DOCTYPE html>
{% load static %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static "users/css/mystyle.css" %}">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <h1>This is the users page</h1>
        <h2> Here are the users </h2>

        <div class='djangtwo'>
            {% if firstnames %}
                <table>
                    <thead>
                        <th> First Name </th>
                        <th> Last Name </th>
                    </thead>

                {% for name in firstnames %}
                <tr>
                    <td> {{ name.first_name }}</td>
                    <td> {{ name.last_name }}</td>
                </tr>

                {% endfor %}
                </table>
                {% else %}
                    <p>No names found</p>
                {% endif %}

        </div>
        
        <script src="" async defer></script>
    </body>
</html>